apiVersion: v1
kind: Service

metadata:
  name: intinv

  spec:
    selector:
      app: intinv
    
    type: LoadBalancer

    ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      