name: Build and Deploy to AKS

on:
  push:
    branches:
      - cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: | 
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Docker Login to ACR
        run: |
          docker login ${{ secrets.ACR_LOGIN_SERVER }} \
            -u ${{ secrets.ACR_USERNAME }} \
            -p ${{ secrets.ACR_PASSWORD }}
      
      - name: Build Docker image
        run: |
          docker build \
            ${{ secrets.ACR_LOGIN_SERVER }}/intinv:latest
      
      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.ACR_LOGIN_SERVER }}/intinv:latest

      - name: Get AKS AZURE_CREDENTIALS
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RESOURCE_GROUP}}
            --name ${{ secrets.AKS_CLUSTER_NAME }}
            --overwrite-existing

      - name: Deploy Application
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      
      - name: Restart Deployment
        run: |
          kubectl rollout restart deployment/intinv
      
      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/intinv